import 'user_model.dart';
import 'child_profile_model.dart';
import 'assessment_result_model.dart';

/// Doctor-specific view combining related records.
/// Not stored directly in DB; generated by MockPatientRepository.
class Patient {
  final UserModel parent;
  final ChildProfile child;
  final AssessmentResult? latestAssessment;
  final List<AssessmentResult> pastAssessments;

  const Patient({
    required this.parent,
    required this.child,
    this.latestAssessment,
    this.pastAssessments = const [],
  });

  // Doctor needs to see full breakdown including trend.
  RiskLevel get currentRiskLevel => latestAssessment?.level ?? RiskLevel.low;

  DateTime? get lastAssessedAt => latestAssessment?.assessedAt;
}
